# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Matthew Clarkson
tagline:          'Marketer, coder, cyclist.'
description:      'Director at <a href="https://simondell.com" target="_blank">SimonDell.com</a>.'
url:              https://mpclarkson.github.io
baseurl:          /

author:
  name:           'Matthew Clarkson'
  url:            https://twitter.com/matt_clarkson

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mpclarkson

excerpt_separator: <!--more-->

gems:
  - jekyll-sitemap
