# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Matthew Clarkson
tagline:          'Founder, marketer, developer, cyclist.'
description:      'Founder at <a href="https://hilenium.com" target="_blank">Hilenium.com</a> and <a href="https://delveintelligence.com" target="_blank">Delve</a>.'
url:              https://mpclarkson.github.io
baseurl:          /

author:
  name:           'Matthew Clarkson'
  url:            https://twitter.com/matt_clarkson

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mpclarkson

excerpt_separator: <!--more-->

gems:
  - jekyll-sitemap
