# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Matthew Clarkson
tagline:          'Founder at hilenium.com, software developer and CMO.'
description:      'Founder at <a href="https://hilenium.com" target="_blank">Hilenium.com</a>, works at <a href="https://scrunch.com" target="_blank">scrunch.com</a>.'
url:              http://mpclarkson.github.io
baseurl:          /

author:
  name:           'Matthew Clarkson'
  url:            https://twitter.com/matt_clarkson

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mpclarkson

excerpt_separator: <!--more-->

gems:
  - jekyll-sitemap
